### ISSUE TITLE
Error occurs "[vite] error applying css transforms:" message.

### ISSUE THREAD

**Issue by ilyoungkim** [wobsoriano/v-dashboard#16]
Windows 10
yarn 1.22.4
node v12.16.1

$> yarn dev 
PS D:\project\v-dashboard> yarn dev
yarn run v1.22.4
$ vite

  Dev server running at:
  > Network:  http://192.168.0.8:3000/
  > Network:  http://192.168.56.1:3000/
  > Local:    http://localhost:3000/

[vite] error applying css transforms:
TypeError: value.charCodeAt is not a function
    at D:\project\v-dashboard\node_modules\tailwindcss\components.css:1:1
    at module.exports (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\parse.js:17:20)
    at new ValueParser (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\index.js:7:18)
    at ValueParser (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\index.js:10:10)
    at transformValue (D:\project\v-dashboard\node_modules\postcss-functions\dist\lib\transformer.js:20:55)
    at D:\project\v-dashboard\node_modules\postcss-functions\dist\lib\transformer.js:72:24
    at D:\project\v-dashboard\node_modules\postcss-functions\dist\index.js:45:18
    at D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:74:18
    at Rule.each (D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:60:16)
    at Rule.walk (D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:71:17)
    at D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:79:24 {
  postcssNode: Declaration {
    raws: {},
    type: 'decl',
    prop: 'font-size',
    value: { lineHeight: '1.5rem' },
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      selector: '.form-input',
      lastEach: 7,
      indexes: [Object],
      parent: [AtRule],
      source: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] }
  }
} 0 [
  TypeError: value.charCodeAt is not a function
      at D:\project\v-dashboard\node_modules\tailwindcss\components.css:1:1
      at module.exports (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\parse.js:17:20)
      at new ValueParser (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\index.js:7:18)
      at ValueParser (D:\project\v-dashboard\node_modules\postcss-functions\node_modules\postcss-value-parser\lib\index.js:10:10)
      at transformValue (D:\project\v-dashboard\node_modules\postcss-functions\dist\lib\transformer.js:20:55)
      at D:\project\v-dashboard\node_modules\postcss-functions\dist\lib\transformer.js:72:24
      at D:\project\v-dashboard\node_modules\postcss-functions\dist\index.js:45:18
      at D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:74:18
      at Rule.each (D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:60:16)
      at Rule.walk (D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:71:17)
      at D:\project\v-dashboard\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:79:24 {
    postcssNode: Declaration {
      raws: {},
      type: 'decl',
      prop: 'font-size',
      value: [Object],
      parent: [Rule],
      source: [Object]
    }
  }
]

![image](https://user-images.githubusercontent.com/18169077/110935119-56c20b80-8372-11eb-8862-5e852b583120.png)

**Comment by yondkoo** [comment]
Did you fix this error?  I've got this error too and don't know how to fix it.

**Comment by wobsoriano** [comment]
Hi, please update and try again thanks
